; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32s3]
platform = https://github.com/platformio/platform-espressif32.git#v4.3.0

board = esp32-s3-devkitc-1

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
framework = arduino
monitor_speed = 115200
monitor_filters = direct, esp32_exception_decoder
monitor_flags = --raw
board_build.partitions = partitions.csv

lib_deps =
;	https://github.com/schreibfaul1/ESP32-audioI2S.git


platform_packages =
     framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#2.0.3-RC1


board_upload.maximum_size = 3145728
board_upload.flash_size = 4MB

;build_flags = -DCORE_DEBUG_LEVEL=0    ; None
;build_flags = -DCORE_DEBUG_LEVEL=1    ; Error
;build_flags = -DCORE_DEBUG_LEVEL=2    ; Warn
;build_flags = -DCORE_DEBUG_LEVEL=4    ; Debug
;build_flags = -DCORE_DEBUG_LEVEL=5    ; Verbose
build_flags =
        -DCORE_DEBUG_LEVEL=3           ; Info
        -DCONFIG_ARDUHAL_LOG_COLORS=1
		-DBOARD_HAS_PSRAM
        -mfix-esp32-psram-cache-issue
        -Wdouble-promotion             ; double to float warnings